---
# Create Template File
    - name: Print Auth Domain
      debug: msg={{auth0_domain}}
    - name: Get Token
      uri:
        url: https://{{auth0_domain}}/oauth/token
        method: POST
        body_format: json
        return_content: yes
        body: {"grant_type":"refresh_token", "refresh_token": "{{refToken}}", "client_id": "{{client_id}}"}
        status_code: 200,204,202
      register: token_response
      ignore_errors: no
    - name: set token & token_type
      set_fact: token="{{ (token_response.content|from_json).access_token }}"
    - set_fact: token_type="{{ (token_response.content|from_json).token_type }}"
    - name: Get OTC Id
      uri:
        url: "http://{{occm_ip}}/occm/api/vsa/working-environments"
        method: GET
        headers:
           Authorization: "{{token_type}} {{ token }}"
           Referer: "Ansible"
        status_code: 200,204,202
        timeout: 180
      register: otc_response
    - name: set we id
      set_fact: we_id="{{otc_response.json.0.publicId}}"
    - name: Print WE ID
      debug: msg={{we_id}}
    - name: Get SvmName
      uri:
        url: "http://{{occm_ip}}/occm/api/vsa/working-environments/{{we_id}}?fields=svmName"
        method: GET
        headers:
           Authorization: "{{token_type}} {{ token }}"
           Referer: "Ansible"
        status_code: 200,204,202
        timeout: 180
      register: svm_response
    - name: set svmName
      set_fact: svmName="{{svm_response.json.svmName}}"
    - name: Print SVM Name
      debug: msg={{svmName}}      
    - name: Create Template File For quote
      template: src=../templates/quote.j2 dest={{ lookup('env', 'PWD') }}/roles/volume/templates/quote.json
    - name: Do Quote OTC
      uri:
        url: "http://{{occm_ip}}/occm/api/aws/ha/volumes/quote"
        method: POST
        headers:
           Authorization: "{{token_type}} {{ token }}"
           Referer: "Ansible"
        body_format: json
        body: "{{ lookup('file','../templates/quote.json') }}"
        status_code: 200,204,202
        timeout: 180
      register: quote_response
    - name: Print Quote
      debug: msg={{quote_response.json.numOfDisks}}
    - debug: msg={{quote_response.json.aggregateName}}
    - name: set numOfDisks & aggregateName
      set_fact: numOfDisks="{{quote_response.json.numOfDisks}}"
    # - set_fact: aggregateName="{{quote_response.json.aggregateName}}"  
    - name: Create Template File For volume
      template: src=../templates/volume.j2 dest={{ lookup('env', 'PWD') }}/roles/volume/templates/volume.json
    - name: Create Volume
      uri:
        url: "http://{{occm_ip}}/occm/api/aws/ha/volumes?createAggregateIfNotFound=true"
        method: POST
        headers:
           Authorization: "{{token_type}} {{ token }}"
           Referer: "Ansible"
        body_format: json
        body: "{{ lookup('file','../templates/volume.json') }}"
        status_code: 200,204,202
        timeout: 180
      register: vol_response
    - name: Print Create volume request ID
      debug: msg={{vol_response.oncloud_request_id}}
    - name: Wait for Volume creation
      uri:
        url: "http://{{occm_ip}}/occm/api/audit/activeTask/{{vol_response.oncloud_request_id}}"
        method: GET
        headers:
           Authorization: "{{token_type}} {{ token }}"
           Referer: "Ansible"
        status_code: 200,204,202
        body_format: json
        timeout: 180
      register: audit_response
      until: audit_response.json.status != 0
      retries: 10
      delay: 20
    - name: set response
      set_fact: status="{{ audit_response.json.status }}"
    - name: Print Volume Result
      debug: msg="Done Success"
      when: status == '1'
    - name: Print Volume Result
      debug: msg="Done Error"
      when: status == '-1'