---
- name: Create CVO Environment for logzio
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - include_role:
        name: cvo
    - include_role:
        name: aggregate
      vars:
        aggregateName: "{{item}}"
        diskSize: 8
      with_items:
         - "{{ aggr2Name }}"
         - "{{ aggr3Name }}"
    - include_role:
        name: iscsiVolume
      vars:
        aggregateName: "{{ item.aggrName }}"
        volName: "{{ item.volName }}"
        iqn: "{{ item.iqn }}"
      with_items:
        - "{{ vars.list }}"